services:
    invoker:
        build:
            context: .
            target: dev
        volumes:
            - .:/app
            - $HOME/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
        working_dir: /app
        tty: true
        stdin_open: true
        env_file:
            - .env
        environment:
            - OTEL_EXPORTER_DISABLED=true
        ports:
            - "8080:8080"

